scheme = [ "https", "http", "mailto" ]
exclude_loopback = true
exclude_path = ["CHANGELOG.md"]
accept = [
    "200..=204",
    "403",  # HuggingFace
    "429",  # GitHub rate limit
    "500..=599"
]
exclude = [
    # blogs
    "^http://lizheming.top",
    "^http://phillipw.info",
    "^https://www.homeboyc.cn",
    "^https://www.iam.rw",
    "^https://bandism.net",
    "^https://blog.thrimbda.com",
    # github disappeared (rename?)
    "^https://github.com/yczheng0$",
    "^https://github.com/aseaday$"
]
