name: changelog

on:
  push:
    tags:
      - v*

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
      - run: git fetch --prune --prune-tags
      - run: git tag -l 'v*'
      - run: ./hack/changelog.sh > CHANGELOG.md
      - uses: peter-evans/create-pull-request@v8
        with:
          title: 'docs: updated CHANGELOG.md'
          commit-message: 'docs: updated CHANGELOG.md'
          branch: create-pull-request/changelog
          signoff: true
