name: envd lint

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/envd-lint.yml'
      - '**.envd'
      - '**.py'
      - '**.ipynb'
      - 'Makefile'
  pull_request:
    paths:
      - '.github/workflows/envd-lint.yml'
      - '**.envd'
      - '**.py'
      - '**.ipynb'
      - 'Makefile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: envd-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Lint
        run: make envd-lint
